Config = {}
Config.ox_lib = true -- set this to true if using ox_lib, if false comment it out in the manifest
Config.ox_inv = true -- set this to true if using ox_inv
Config.debugprints = true -- set this to turn on prints
Config.namechangeitem = "namechanger" -- set this to usable item name (could be good for monetizations?)
Config.marriagecertificate = "marriagecertificate" -- set this to item for a judge or someone like a pastor to give an item to change name on use
Config.filledcertificate = "filledcertificate" -- set this to item for a filled certificate to apply on use (by a judge or something)
Config.jobcheck = true -- set this to true to prevent any job from randomly creating these, I cant imagine the chaos that would come otherwise
Config.jobname = "police" -- set this to a desired job name that can use this item, to use this Config.jobcheck must be set to true